crm/urls.py
from django.contrib.auth import views
from django.urls import include, path

app_name = 'crm'

urlpatterns = [
    path('', include('common.urls', namespace="common")),
    path('', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('leads/', include('leads.urls', namespace="leads")),
    path('contacts/', include('contacts.urls', namespace="contacts")),
    path('opportunities/', include('opportunity.urls', namespace="opportunities")),
    path('cases/', include('cases.urls', namespace="cases")),
    path('emails/', include('emails.urls', namespace="emails")),
    # path('planner/', include('planner.urls', namespace="planner")),
    path('logout/', views.logout, {'next_page': '/login/'}, name="logout"),
]

leads/urls.py
from django.urls import path
from leads.views import (
    LeadListView, CreateLeadView, LeadDetailView, UpdateLeadView, DeleteLeadView, ConvertLeadView,
    GetLeadsView, AddCommentView, UpdateCommentView, DeleteCommentView)


app_name = 'leads'


urlpatterns = [
    path('list/', LeadListView.as_view(), name='list'),
    path('create/', CreateLeadView.as_view(), name='add_lead'),
    path('<int:pk>/view/', LeadDetailView.as_view(), name="view_lead"),
    path('<int:pk>/edit/', UpdateLeadView.as_view(), name="edit_lead"),
    path('<int:pk>/delete/', DeleteLeadView.as_view(), name="remove_lead"),
    path('<int:pk>/convert/', ConvertLeadView.as_view(), name="leads_convert"),

    path('get/list/', GetLeadsView.as_view(), name="get_lead"),

    path('comment/add/', AddCommentView.as_view(), name="add_comment"),
    path('comment/edit/', UpdateCommentView.as_view(), name="edit_comment"),
    path('comment/remove/', DeleteCommentView.as_view(), name="remove_comment"),
]

cases/models.py
from django.db import models
from django.utils.translation import pgettext_lazy
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType

from accounts.models import Account
from contacts.models import Contact
from common.models import User, Team
from common.utils import CASE_TYPE, PRIORITY_CHOICE, STATUS_CHOICE


class Case(models.Model):
    name = models.CharField(
        pgettext_lazy("Name of the case", "Name"),
        max_length=64)
    status = models.CharField(choices=STATUS_CHOICE, max_length=64)
    priority = models.CharField(choices=PRIORITY_CHOICE, max_length=64)
    case_type = models.CharField(choices=CASE_TYPE, max_length=255, blank=True, null=True, default='')
    account = models.ForeignKey(Account, on_delete=models.CASCADE, blank=True, null=True)
    contacts = models.ManyToManyField(Contact)
    closed_on = models.DateTimeField()
    description = models.TextField(blank=True, null=True)
    assigned_to = models.ManyToManyField(User, related_name='case_assigned_users')
    teams = models.ManyToManyField(Team)
    created_by = models.ForeignKey(User, related_name='case_created_by', on_delete=models.CASCADE)
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    is_active = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.name

    def get_meetings(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Meeting", status="Planned")

    def get_completed_meetings(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Meeting").exclude(status="Planned")

    def get_tasks(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(content_type=content_type, object_id=self.id, event_type="Task", status="Planned")

    def get_completed_tasks(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Task").exclude(status="Planned")

    def get_calls(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(content_type=content_type, object_id=self.id, event_type="Call", status="Planned")

    def get_completed_calls(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Call").exclude(status="Planned")

    def get_assigned_user(self):
        return User.objects.get(id=self.assigned_to.id)

common/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager

from common.utils import COUNTRIES, ROLES


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=100, unique=True)
    first_name = models.CharField(max_length=150, blank=True)
    last_name = models.CharField(max_length=150, blank=True)
    email = models.EmailField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(('date joined'), auto_now_add=True)
    role = models.CharField(max_length=50, choices=ROLES)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', ]

    objects = UserManager()

    def get_short_name(self):
        return self.username

    def __unicode__(self):
        return self.email


class Address(models.Model):
    address_line = models.CharField(_("Address"), max_length=255, blank=True, null=True)
    street = models.CharField(_("Street"), max_length=55, blank=True, null=True)
    city = models.CharField(_("City"), max_length=255, blank=True, null=True)
    state = models.CharField(_("State"), max_length=255, blank=True, null=True)
    postcode = models.CharField(_("Post/Zip-code"), max_length=64, blank=True, null=True)
    country = models.CharField(max_length=3, choices=COUNTRIES, blank=True, null=True)

    def __str__(self):
        return self.city if self.city else ""


class Team(models.Model):
    name = models.CharField(max_length=55)
    members = models.ManyToManyField(User)

    def __str__(self):
        return self.name


class Comment(models.Model):
    case = models.ForeignKey('cases.Case', blank=True, null=True, related_name="cases", on_delete=models.CASCADE)
    comment = models.CharField(max_length=255)
    commented_on = models.DateTimeField(auto_now_add=True)
    commented_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    account = models.ForeignKey(
        'accounts.Account', blank=True, null=True, related_name="accounts_comments", on_delete=models.CASCADE)
    lead = models.ForeignKey('leads.Lead', blank=True, null=True, related_name="leads", on_delete=models.CASCADE)
    opportunity = models.ForeignKey(
        'opportunity.Opportunity', blank=True, null=True, related_name="opportunity_comments", on_delete=models.CASCADE)
    contact = models.ForeignKey(
        'contacts.Contact', blank=True, null=True, related_name="contact_comments", on_delete=models.CASCADE)

    def get_files(self):
        return Comment_Files.objects.filter(comment_id=self)


class Comment_Files(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    updated_on = models.DateTimeField(auto_now_add=True)
    comment_file = models.FileField("File", upload_to="comment_files", default='')

    def get_file_name(self):
        if self.comment_file:
            return self.comment_file.path.split('/')[-1]
        else:
            return None

leads/models.py
from django.db import models
from django.utils.translation import pgettext_lazy
from django.utils.translation import ugettext_lazy as _

from accounts.models import Account
from common.models import User, Address, Team
from common.utils import LEAD_STATUS, LEAD_SOURCE


class Lead(models.Model):
    title = models.CharField(
        pgettext_lazy("Treatment Pronouns for the customer", "Title"),
        max_length=64, blank=True, null=True)
    first_name = models.CharField(("First name"), max_length=255)
    last_name = models.CharField(("Last name"), max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=20, null=True, blank=True)
    account = models.ForeignKey(Account, related_name='Leads', on_delete=models.CASCADE, blank=True, null=True)
    status = models.CharField(_("Status of Lead"), max_length=255,
                              blank=True, null=True, choices=LEAD_STATUS)
    source = models.CharField(_("Source of Lead"), max_length=255,
                              blank=True, null=True, choices=LEAD_SOURCE)
    address = models.ForeignKey(Address, related_name='leadaddress', on_delete=models.CASCADE, null=True, blank=True)
    website = models.CharField(_("Website"), max_length=255, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    assigned_to = models.ManyToManyField(User, related_name='lead_assigned_users')
    teams = models.ManyToManyField(Team)
    account_name = models.CharField(max_length=255, null=True, blank=True)
    opportunity_amount = models.DecimalField(
        _("Opportunity Amount"), decimal_places=2, max_digits=12,
        blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='lead_created_by', on_delete=models.CASCADE)
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    is_active = models.BooleanField(default=False)
    enquery_type = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        ordering =['-created_on']

    def __str__(self):
        return self.first_name + self.last_name

leads/forms.py
from django import forms
from leads.models import Lead
from common.models import Address, Comment


class LeadForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        assigned_users = kwargs.pop('assigned_to', [])
        super(LeadForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}
        if self.data.get('status') == 'converted':
            self.fields['account_name'].required = True
        self.fields['assigned_to'].queryset = assigned_users
        self.fields['assigned_to'].required = False
        self.fields['teams'].required = False
        self.fields['phone'].required = True
        self.fields['first_name'].widget.attrs.update({
            'placeholder': 'First Name'})
        self.fields['last_name'].widget.attrs.update({
            'placeholder': 'Last Name'})
        self.fields['account_name'].widget.attrs.update({
            'placeholder': 'Account Name'})

    class Meta:
        model = Lead
        fields = ('assigned_to', 'teams', 'first_name', 'last_name', 'account_name', 'title',
                  'phone', 'email', 'status', 'source', 'website', 'address', 'description'
                  )

    def clean_phone(self):
        client_phone = self.cleaned_data.get('phone', None)
        if client_phone:
            try:
                if int(client_phone) and not client_phone.isalpha():
                    ph_length = str(client_phone)
                    if len(ph_length) < 10 or len(ph_length) > 13:
                        raise forms.ValidationError('Phone number must be minimum 10 Digits and maximum 13 Digits')
            except (ValueError):
                raise forms.ValidationError('Phone Number should contain only Numbers')
            return client_phone


class LeadCommentForm(forms.ModelForm):
    comment = forms.CharField(max_length=64, required=True)

    class Meta:
        model = Comment
        fields = ('comment', 'lead', 'commented_by')

leads/templates/leads_list.html
<table class="table">
   <thead>
      <tr>
         <th width="50%">
            <a href='#'>
            Name
            </a>
            <span class="caret"></span>
         </th>
         <th>
            <a href="#">
            Email
            </a>
         </th>
      </tr>
   </thead>
   <tbody>
      {% ifequal leads|length  0 %}
      <tr>
         <td class="cell">
            NO LEADS FOUND!!
         </td>
      </tr>
      {% endifequal %}
      {% for lead in leads %}
      <tr>
         <td class="cell">
            <a class="cell parentname" id="{{ lead.id }}">
            {{ lead.first_name }}
            </a>
         </td>
         <td class="cell parentemail">
            {{ lead.email }}
         </td>
      </tr>
      {% endfor %}
   </tbody>
</table>

leads/templates/view_leads.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block breadcrumb %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'leads:list' %}">Leads</a></li>
    <li class="breadcrumb-item active">View</li>
  </ol>
</nav>

{%endblock%}
{% block content %}
<div class="main_container" id="maincontainer">
  <div class="overview_form_block row marl justify-content-center">
    <div class="col-md-8">
      <div class="card">
       
        <div class="card-body" id="datashow">
         <div class="card-title">
          <h5>
            Overview
            <span class="float-right" style="margin-top: 0px">
              <div class="dropdown buttons_row">
                <button class="btn btn-primary dropdown-toggle save" type="button" data-toggle="dropdown">Actions
                <span class="caret"></span></button>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'leads:edit_lead' lead_record.id %}" >Edit</a></li>
                  <li class="delete_contact" ><a href="{% url 'leads:remove_lead' lead_record.id %}" id="remove_contact">REMOVE</a></li>
                  <li><a href="{% url 'leads:leads_convert' lead_record.id %}" class="btn btn-info" role="button">Convert</a></li>
                </ul>
              </div>
            </span>
          </h5>
        </div>
          <div class="row marl">
            <div class="col-md-6">
              <div class="filter_col col-md-12" id="iname">
                <div class="form-group" >
                  <label class="lead_field_label" for="id_name" data-name="name">Name</label>
                  <div class="lead_field" id="lead_name" data-name="name">{{ lead_record.first_name }} {{ lead_record.last_name }}</div>
                </div>
              </div>
              <div class="filter_col col-md-12">
                {% if lead_record.account_name %}
                <div class="form-group">
                  <label class="lead_field_label" for="id_contact_account" data-name="name">Account Name</label>
                  <div class="lead_field" id ="contact_account" data-name="name">{{ lead_record.account_name }}</div>
                </div>
                {% endif %}
              </div>
              <div class="filter_col col-md-12">
                {% if lead_record.title %}
                <div class="form-group">
                  <label class="lead_field_label" for="id_title" data-name="name">Title</label>
                  <div class="lead_field" id="lead_title" data-name="name">{{ lead_record.title }}</div>
                </div>
                {% endif %}
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="lead_field_label" for="id_phone" data-name="name">Phone</label>
                  <div class="lead_field" id="lead_phone" data-name="name">{{ lead_record.phone }}</div>
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="lead_field_label" for="id_email" data-name="name">Email</label>
                  <div class="lead_field" id="lead_email" data-name="name">{{ lead_record.email }}</div>
                </div>
              </div>
            </div>
            <div class="col-md-12">
              <div class="filter_col col-md-12">
                {% if lead_record.status %}
                <div class="form-group">
                  <label class="lead_field_label" for="id_status" data-name="name">Status</label>
                  <div class="lead_field" id="lead_status" data-name="name">{{ lead_record.status }}</div>
                </div>
                {% endif %}
              </div>
              <div class="filter_col col-md-12">
                {% if lead_record.source %}
                <div class="form-group">
                  <label class="lead_field_label" for="id_source" data-name="name">Source</label>
                  <div class="lead_field" id="lead_source" data-name="name">{{ lead_record.source }}</div>
                </div>
                {% endif %}
              </div>
              <div class="filter_col col-md-12">
                {% if lead_record.website %}
                <div class="form-group">
                  <label class="lead_field_label" for="id_website" data-name="name">Website</label>
                  <div class="lead_field" id="lead_website" data-name="name">{{ lead_record.website }}</div>
                </div>
                {% endif %}
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  {% if lead_record.address.address_line or lead_record.address.street or lead_record.address.city or lead_record.address.state or lead_record.address.postcode or lead_record.address.country %}
                  <label class="lead_field_label" for="id_address" data-name="name" >Billing Address</label>
                  <div class="lead_field" id="lead_address" data-name="name">
                    {% if lead_record.address.address_line %}
                      Address Line:{{lead_record.address.address_line}}</br>
                    {% endif %}
                    {% if lead_record.address.street %}
                      Street:{{ lead_record.address.street }}</br>
                    {% endif %}
                    {% if lead_record.address.city %}
                      City: {{ lead_record.address.city }}</br>
                    {% endif %}
                    {% if lead_record.address.state %}
                      State:{{ lead_record.address.state }}</br>
                    {% endif %}
                    {% if lead_record.address.postcode %}
                      Post Code:{{ lead_record.address.postcode }}</br>
                    {% endif %}
                    {% if lead_record.address.country %}
                      Country: {{ lead_record.address.get_country_display }}
                    {% endif %}
                  </div>
                  {% endif %}
                </div>
              </div>
              <div class="filter_col col-md-12">
                {% if lead_record.description %}
                <div class="form-group">
                  <label class="lead_field_label" for="id_description" data-name="name" >Description</label>
                  <div class="lead_field" id="lead_description" data-name="name">{{ lead_record.description }}</div>
                </div>
                {% endif %}
              </div>
            </div>
            <div class="col-md-12">
                <div class="created_information">
                  Created by <b>{{ lead_record.created_by }}</b> created on <i><b>{{ lead_record.created_on }}</b></i> 
                </div>
              </div>
          </div>
        </div>
        <!-- Comments Section starts-->
       
        <div class="card-body mar-top" id="datashow">
         <div class="card-title view-pad">
          <h5>Comments </h5>
        </div>
          <div class="row marl">
            <div class="col-md-12">
              <form id="comment_form" method="POST" enctype="multipart/form-data">
                <div class="form-group ">
                  <textarea class="form-control" textarea cols="40" rows="3" id="id_comments" name="comment" placeholder="Submit Your Comments Here"></textarea><span><i id="CommentError" style="display:none; color:red"></i></span>
                  </br>
                  <div class="buttons_row">
                  <button class="btn btn-default save" style="text-align: center;" id="comment_submit">Submit</button>
                  </div>
                </div>
                <input type="hidden" value="{{lead_record.id}}" name="leadid">
              </form>
              <ul class="list-group" id="comments_div">
                {% for comment in comments %}
                <li class="list-group-item list-row" id="comment{{comment.id}}">
                  <div class="float-right right-container">
                    <div class="list-row-buttons btn-group float-right">
                      <button class="btn btn-link btn-sm dropdown-toggle" data-toggle="dropdown" type="button"><span class="caret"></span></button>
                      <ul class="dropdown-menu text-center">
                        <li>
                          <a class="action" onclick="edit_comment({{comment.id}})">Edit</a>
                        </li>
                        <li>
                          <a class="action" onclick="remove_comment({{comment.id}})">Remove</a>
                        </li>
                      </ul>
                    </div>
                  </div>
                  <div class="stream-post-container" id="comment_name{{comment.id}}"><pre>{{ comment.comment }}</pre></div>
                  <div class="stream-container">
                    <pre class="float-left">{{ comment.commented_by }}</pre>
                    <pre class="float-right">{{ comment.commented_on }}</pre>
                  </div>
                </li>
                {% endfor %}
              </ul>
            </div>
          </div>
          <div class="modal fade" id="Comments_Leads_Modal" role="dialog" data-keyboard="false" data-backdrop="static">
            <div class="modal-dialog modal-lg">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">Update Your Comment</h4>
                </div>
                <form id="comment_edit_form" method="POST" >
                  <div class="modal-body">
                    <div class="form-group">
                      <textarea class="form-control" textarea cols="40" rows="3" id="id_editcomment" name="comment" placeholder="Submit Your Comments"></textarea><span><i id="CommentEditError" style="display:none; color:red"></i></span>
                      <input type="hidden" value="{{ lead.id }}" name="leadid">
                      <input type="hidden" value="" name="commentid" id="commentid">
                    </div>
                  </div>
                  <div class="modal-footer">
                    <button class="btn btn-default save" id="comment_edit" type="submit">Update</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <!-- Comments Section Ends-->
      </div>
    </div>
    <tr id="meeting{{ meeting.id }}">
   
  </div>
</div>
{% endblock %}
{% block js_block %}
 <script src="{% static 'js/calls.js' %}"></script>
 <script src="{% static 'js/meetings.js' %}"></script>
 <script type="text/javascript">
$("#comment_form").submit(function (e) {
  e.preventDefault()
  var formData = new FormData($("#comment_form")[0]);
  $.ajax({
    url: "{% url 'leads:add_comment' %}",
    type: "POST",
    data: formData,
    cache: false,
    contentType: false,
    processData: false,
    success: function (data) {
      if (data.error) {
        $("#CommentError").html(data.error).show()
      } else {
        d = new Date(data.commented_on);
        $("#comments_div").prepend("<li class='list-group-item list-row' id='comment" + data.comment_id + "'>" +
          "<div class='float-right right-container'>" +
          "<div class='list-row-buttons btn-group float-right'>" +
          "<button class='btn btn-link btn-sm dropdown-toggle' data-toggle='dropdown' type='button'><span class='caret'></span></button>" +
          "<ul class='dropdown-menu text-center'>" +
          "<li><a class='action' onclick='edit_comment(" + data.comment_id + ")'>Edit</a></li>" +
          "<li><a class='action' onclick='remove_comment(" + data.comment_id + ")''>Remove</a></li></ul></div></div>" +
          "<div class='stream-post-container' id='comment_name"+data.comment_id+"'><pre>"+data.comment+"</pre></div>"+
          "<div class='stream-container'><pre class='float-left'>"+data.commented_by+"</pre><pre class='float-right'>"+d.toGMTString()+"</pre></div>"+
          "<div class='stream-date-container' id='comment_file_div"+data.comment_id+"'><div id='new_comment"+data.comment_id+"'</div></div></li>"
        )
        $("#id_comments").val("")
        alert("Comment Submitted")
        $("#CommentError").html("")
      }
    }
  })
})


function edit_comment(x) {
  $('#Comments_Leads_Modal').modal('show');
  comment = $("#comment_name" + x).text()
  $("#commentid").val(x)
  $("#id_editcomment").val(comment)
}

$("#comment_edit").click(function (e) {
  e.preventDefault()
  var formData = new FormData($("#comment_edit_form")[0]);
  $.ajax({
    url: "{% url 'leads:edit_comment' %}",
    type: "POST",
    data: formData,
    cache: false,
    contentType: false,
    processData: false,
    success: function (data) {
      if (data.error) {
        $("#CommentEditError").html(data.error).show()
      } else {
        $("#comment_name" + data.commentid).html('<pre>' + data.comment + '</pre>')
        $('#Comments_Leads_Modal').modal('hide');
        $("#id_editcomment").val("")
        $("#CommentEditError").html("")
      }
    }
  })
})


function HideError(e) {
  $("#CommentError").hide()
}

function remove_comment(x) {
  var con = confirm("Do you want to Delete it for Sure!?")
  if (con == true) {
    $.post('{% url "leads:remove_comment" %}', {
      "comment_id": x
    }, function (data) {
      if (data.error) {
        alert(data.error)
      } else {
        $("#comment" + data.cid).remove()
      }
    })
  }
}
</script>
{% endblock js_block %}